### ISSUE TITLE
Action Sheets are hiding (Alert style)

### ISSUE THREAD

**Issue by DD12-1916** [tomaszpoliszuk/AlertController#2]
When I set the Action Sheet style to (Alert), the action sheet menus do not appear in Cydia. So far, this includes the options for the 'Modify' button in packages and Flame's options for adding sources. Just a minor thing.

By the way, I'm also using BlurryAlerts, if that amounts to anything and thanks to your tweak, the Action Sheets look waaaaay cooler! You're awesome!

**Comment by tomaszpoliszuk** [comment]
Please check if your installed version of AlertController is 1.3.1 because this bug was fixed in it and report back.

**Comment by DD12-1916** [comment]
It is indeed 1.3.1

Maybe an iPad Incompatibility?

I'm using an iPad Air 2

**Comment by tomaszpoliszuk** [comment]
Could you turn off every other tweak - for example using iCleaner - and check again (this step is to check if issue is due to incompatibility with iPad or with other tweak)?

**Comment by DD12-1916** [comment]
Oh yeah, I am sorry I forgot about doing that. Anyway, I just enabled two addons, Alert Controller and PreferenceLoader, anddd... no luck, it still doesn't work. I tried both the 'delete' function in Photos, and once again, the 'Modify' button in Cydia, and only the Alert-style Action Sheet worked in Photos.

Oh yeah, another minor thing, it appears that the 'Square Corners' option doesn't work for the Default Action Sheet style. I tried to respring the device even though the other options did not need to, and yep, doesn't work either. Just wanted to let you know so maybe you could kill two stones with one bird.

**Comment by tomaszpoliszuk** [comment]
Could you contact me using option in Package Manager (tap on author field and then again on author field) - it will autogenerate additional information for me.

Please add information that it's you (or link to this issue).

**Comment by tomaszpoliszuk** [comment]
Could you contact me using option in package manager (in Cydia you can tap on author field and then again on author field) - it will autogenerate additional information for me.

Please add information that it's you (or link to this issue).

**Comment by DD12-1916** [comment]
Okay sure!

**Comment by DD12-1916** [comment]
So I just sent the Email, but I am not sure if it went through. The Mail application did not indicate if any error occurred, but the Gmail application did; apparently, the Email is invalid now?

**Comment by tomaszpoliszuk** [comment]
I got it - I will analyse content and get back to you via that email but can't say how fast (maybe weekend?).

**Comment by DD12-1916** [comment]
Sure! It's totally up to you

**Comment by tomaszpoliszuk** [comment]
I've tried to contact you (via email) in previous week but you didn't responded, can you tell me if updated version (1.4.1) solved your issue?

**Comment by DD12-1916** [comment]
> I've tried to contact you (via email) in previous week but you didn't responded, can you tell me if updated version (1.4.1) solved your issue?

Oh yeah sorry about that, been quite busy. Anyway, I am currently in the process of checking if the latest update has fixed this issue.

**Comment by DD12-1916** [comment]
After a little bit of tinkering, it appears that the issue persists, correctly functioning in the stock Photos application, while malfunctioning in the Cydia application. 
As for the 'Square Corners' issue, the option still does not work as intended when either the Alerts or Action Sheets have been set to appear as Action Sheets, even after performing a LDRestart. Moreover, I found out that when the 'Square Corners' option is turned on for the Action Sheet style, it affects both Alerts and Action Sheets that have been set to appear as Alerts.
Turns out, the latest update somehow managed to break compatibility with the 'Blurry Alerts' tweak as far as I am aware of, as I couldn't find the option to downgrade your tweak to the update before the current one.

**Comment by tomaszpoliszuk** [comment]
Let's move conversation to email for a moment :)

**Comment by DD12-1916** [comment]
Hmmm... something's weird, because I can't see your email at all, nor the email I sent to you through Cydia.
I'll try to send another email, and maybe you could reply to that instead

**Comment by tomaszpoliszuk** [comment]
If you sent one with info "Maybe this email will go through?" then it did - I've also replied to our older emails - if none of those works maybe DM me on twitter (if you use it)?
https://twitter.com/TomaszPoliszuk

**Comment by DD12-1916** [comment]
Hello there! I am really sorry about my lack of activity on this issue, as I have been quite the busy person this past month. Unfortunately, this will continue as my iPad unceremoniously decided to update itself to iPadOS 14.2 : / (may your and the others' awesome tweaks rest in peace for now)
I will close this issue now since no one else seems to experience this bug.
Anyway, thank you so much for attending to this issue!

**Comment by tomaszpoliszuk** [comment]
Sorry for your loss :(
